-- 코드를 입력하세요
SELECT a.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT a INNER JOIN FOOD_ORDER b
ON a.PRODUCT_ID = b.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY a.PRODUCT_ID
ORDER BY 3 DESC, 1