-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, a.PT_NO, a.MCDP_CD, DR_NAME, APNT_YMD
FROM (PATIENT p RIGHT JOIN APPOINTMENT a
ON p.PT_NO = a.PT_NO) JOIN DOCTOR d
ON d.DR_ID = a.MDDR_ID
WHERE APNT_YMD LIKE '2022-04-13%'
AND a.MCDP_CD = 'CS'
AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD